version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: .Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - /client/node_modules
    links:
      - server
    networks:
      - webappnetwork
  server:
    build:
      context: ./server
      dockerfile: .Dockerfile
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - ./server:/server
      - /server/node_modules
    depends_on:
      - mongodb
    networks:
      - webappnetwork
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - ./data-node:/data/db
    ports:
      - "27017:27017"
    command: mongod --noauth
    networks:
      - webappnetwork
networks:
  webappnetwork:
    driver: bridge